//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerFile
    {
        public int ID { get; set; }
        public int IncomeTypeID { get; set; }
        public Nullable<int> ChannelID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SubProductIID { get; set; }
        public Nullable<int> LoanBankID { get; set; }
        public string Vehicle { get; set; }
        public Nullable<decimal> LoanAmont { get; set; }
        public Nullable<int> Tenure { get; set; }
        public Nullable<decimal> EMI { get; set; }
        public Nullable<System.DateTime> EMIDate { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public string PropertyAddress { get; set; }
        public string Pendency { get; set; }
        public System.DateTime DateAdded { get; set; }
        public System.DateTime DateModified { get; set; }
    
        public virtual Channel Channel { get; set; }
        public virtual LoanBank LoanBank { get; set; }
        public virtual Product Product { get; set; }
        public virtual PropertyType PropertyType { get; set; }
        public virtual SubProduct SubProduct { get; set; }
    }
}
