//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Financial.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirmRegistration
    {
        public int ID { get; set; }
        public string FirmName { get; set; }
        public string ContactPersonName { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string Email { get; set; }
        public int CountryMasterID { get; set; }
        public int StateMasterID { get; set; }
        public string City { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> SMSLimit { get; set; }
        public Nullable<int> OTP { get; set; }
        public Nullable<int> IsOtpUsed { get; set; }
    
        public virtual CountryMaster CountryMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
    }
}
